name: Backend CI/CD

on:
  push:
    branches: ['main']
    paths:
      - 'backend/**'  # solo se dispara si hay cambios en /backend

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t nico4lvarez/backend-taller3:latest .

      - name: Push Docker image
        run: docker push nico4lvarez/backend-taller3:latest
