name: Deploy Frontend to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change directory to frontend
        run: cd frontend

      - name: Install dependencies
        run: npm install && npm install -g firebase-tools
        working-directory: ./frontend

      - name: Build application
        run: |
          CI='' npm run build
        working-directory: ./frontend

      - name: Deploy to Firebase
        run: npm install firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        working-directory: ./frontend
